[platformio]
workspace_dir = local/pio
build_dir = build/pio

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = fastled/FastLED
upload_port = /dev/ttyUSB0
upload_speed = 115200
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -DNDEBUG -std=gnu++17
build_src_filter =
    +<background_crc.cpp>
    +<colors.cpp>
    +<compositor.cpp>
    +<decoder.cpp>
    +<gamma.cpp>
    +<firmware/background_store.cpp>
    +<firmware/esp_device_identity.cpp>
    +<firmware/esp_platform_clock.cpp>
    +<firmware/diagnostics.cpp>
    +<firmware/discovery_service.cpp>
    +<firmware/esp_tcp_transport.cpp>
    +<firmware/esp_udp_transport.cpp>
    +<engine.cpp>
    +<firmware/wifi_manager.cpp>

[env:esp32dev_led0_sanity]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = fastled/FastLED
upload_port = /dev/ttyUSB0
upload_speed = 115200
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -DNDEBUG -std=gnu++17
build_src_filter =
    +<firmware/led0_sanity.cpp>
