#pragma once

// Pluggable system-level operations. Owned by the firmware app loop /
// sim main, NOT by SystemHandler. The handler signals
// PollResult::reboot_requested; the outer loop calls reboot() after the
// ACK has been flushed to the controller.
//
// Two impls:
//   - EspSystemPlatform: deferred ESP.restart() with a short flush window.
//   - SimSystemPlatform: _exit(SIM_REBOOT_EXIT_CODE) so the supervisor
//                        re-execs the binary. RAM is wiped naturally;
//                        boot_token is regenerated by the normal startup
//                        path. File-backed background storage survives
//                        re-exec because the file does. See the sim
//                        launcher contract in drafts/TODO.md.

class SystemPlatform {
public:
    virtual ~SystemPlatform() = default;

    // Reboot the device. ESP version restarts the chip; sim version
    // exits with the reboot sentinel so the supervisor relaunches.
    // Either way the controller sees the TCP connection drop and a
    // fresh DEVICE_HELLO with a new boot_token.
    virtual void reboot() = 0;

    // TODO: a future "factory reset" command (clear NVS, clear background)
    // would land here next. Out of scope for v3.
};
